name: Deploy Factory Proxy
on:
  push:
    branches: [ main ]
    paths:
      - src/ERC20FactoryProxy.sol
  workflow_dispatch:
jobs:
  deploy-contract:
    runs-on: ubuntu-latest
    env:
      CONTRACT_NAME: FactchainNFT
      CHAIN_ID: 11155111
      ETH_RPC_URL: ${{ secrets.RPC_ETH_SEPOLIA_HTTPS }}
      PRIVATE_KEY: ${{ secrets.DEPLOYER_PK }}
      ETHERSCAN_URL: https://sepolia.etherscan.io
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_SEPOLIA_API_KEY }}
      OWNER_ADDRESS: ${{ vars.OWNER_ADDRESS }}
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: YBadiss/deploy-contract@v1
        with:
          contract-name: 'ERC20FactoryProxy'
          parent-dir: '.'
          chain-id: '11155111'
          rpc-url: ${{ secrets.RPC_ETH_SEPOLIA_HTTPS }}
          deployer-pk: ${{ secrets.DEPLOYER_PK }}
          constructor-args: '${{ vars.OWNER_ADDRESS }}'
          verify: true
          etherscan-url: 'https://sepolia.etherscan.io'
          etherscan-api-key: ${{ secrets.ETHERSCAN_SEPOLIA_API_KEY }}